apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/shirocola/devops-assignment.git'
    targetRevision: HEAD
    path: 'k8s/overlays/prod'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: hello-api-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true