name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DEPLOY_ARGOCD_APP: ${{ vars.DEPLOY_ARGOCD_APP }}  # Set DEPLOY_ARGOCD_APP globally

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'

      - name: Build the Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/hello-api:${{ github.sha }} .
        shell: bash

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push the Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/hello-api:${{ github.sha }}
        shell: bash

      - name: Update Image Tag and Name in K8s Overlay
        run: |
          sed -i "s|newTag:.*|newTag: '${{ github.sha }}'|g" k8s/overlays/prod/kustomization.yaml
          sed -i "s|newName:.*|newName: '${{ secrets.DOCKERHUB_USERNAME }}/hello-api'|g" k8s/overlays/prod/kustomization.yaml
        shell: bash

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update image tag to ${{ github.sha }}
          file_pattern: k8s/overlays/prod/kustomization.yaml
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com

      - name: Apply ArgoCD Application (Optional)
        if: ${{ env.DEPLOY_ARGOCD_APP == 'true' }}
        run: |
          # Install Google Cloud SDK and gke-gcloud-auth-plugin
          echo "Installing Google Cloud SDK and GKE auth plugin..."
          sudo apt-get update && sudo apt-get install -y apt-transport-https ca-certificates gnupg
          
          # Add the Google Cloud public key
          curl -sSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo tee /usr/share/keyrings/cloud.google.gpg >/dev/null
          
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          sudo apt-get update && sudo apt-get install -y google-cloud-cli google-cloud-cli-gke-gcloud-auth-plugin
          
          # Create the .kube directory if it doesn't exist
          mkdir -p $HOME/.kube

          # Decode and write the KUBECONFIG
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config
          
          # Apply ArgoCD application
          kubectl apply -f argocd/argocd-app.yaml -n argocd
        shell: bash

