name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DEPLOY_ARGOCD_APP: ${{ vars.DEPLOY_ARGOCD_APP }}  # Set DEPLOY_ARGOCD_APP globally

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'

      - name: Build the Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/hello-api:${{ github.sha }} .
        shell: bash

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push the Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/hello-api:${{ github.sha }}
        shell: bash

      - name: Update Image Tag and Name in K8s Overlay
        run: |
          sed -i "s|newTag:.*|newTag: '${{ github.sha }}'|g" k8s/overlays/prod/kustomization.yaml
          sed -i "s|newName:.*|newName: '${{ secrets.DOCKERHUB_USERNAME }}/hello-api'|g" k8s/overlays/prod/kustomization.yaml
        shell: bash

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update image tag to ${{ github.sha }}
          file_pattern: k8s/overlays/prod/kustomization.yaml
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com

      - name: Apply ArgoCD Application (Optional)
        if: ${{ env.DEPLOY_ARGOCD_APP == 'true' }}
        run: |
          # Install prerequisites
          sudo apt-get update && sudo apt-get install -y apt-transport-https ca-certificates gnupg

          # Import the Google Cloud public key
          curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg

          # Add the Google Cloud SDK repository to apt sources
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list

          # Update and install Google Cloud SDK and GKE auth plugin
          sudo apt-get update && sudo apt-get install -y google-cloud-cli google-cloud-cli-gke-gcloud-auth-plugin

          # Write JSON credentials to gcloud-key.json
          printf "%s" "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}" > $HOME/gcloud-key.json
          
          # Display and validate JSON format
          cat $HOME/gcloud-key.json | jq .

          gcloud auth activate-service-account --key-file=$HOME/gcloud-key.json
          gcloud config set project devops-assignment-439616
          
          # Create the .kube directory if it doesn't exist
          mkdir -p $HOME/.kube

          # Decode and write the KUBECONFIG
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config
          
          # Apply ArgoCD application
          kubectl apply -f argocd/argocd-app.yaml -n argocd
        shell: bash

