name: CI Pipeline

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  ARGOCD_INSTALLED: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: "projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "github-actions-sa@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com"

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Determine Changed Files
        id: changed-files
        run: |
          git fetch origin
          if [ -z "${{ github.event.before }}" ]; then
            echo "changed_files=''" >> $GITHUB_ENV
          else
            git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed_files.txt
            echo "changed_files=$(cat changed_files.txt | tr '\n' ' ')" >> $GITHUB_ENV
          fi

      - name: Check for Application Changes
        id: app-changes
        run: |
          if [[ "${{ env.changed_files }}" =~ "Dockerfile" || "${{ env.changed_files }}" =~ "main.go" ]]; then
            echo "build=true" >> $GITHUB_ENV
          else
            echo "build=false" >> $GITHUB_ENV
          fi

      - name: Set up Go
        if: env.build == 'true'
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'

      - name: Build and Push Docker Image
        if: env.build == 'true'
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/hello-api:${{ github.sha }} .
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/hello-api:${{ github.sha }}
        shell: bash

      - name: Update Kubernetes Image Tag
        if: env.build == 'true'
        run: |
          sed -i "s|newTag:.*|newTag: '${{ github.sha }}'|g" k8s/overlays/prod/kustomization.yaml
          sed -i "s|newName:.*|newName: '${{ secrets.DOCKERHUB_USERNAME }}/hello-api'|g" k8s/overlays/prod/kustomization.yaml
        shell: bash

      - name: Commit and Push Changes
        if: env.build == 'true'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update image tag to ${{ github.sha }}
          file_pattern: k8s/overlays/prod/kustomization.yaml

      - name: Apply ArgoCD Application
        if: env.build == 'true' && env.ARGOCD_INSTALLED == 'true'
        run: |
          sudo apt-get update && sudo apt-get install -y apt-transport-https ca-certificates gnupg
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          sudo apt-get update && sudo apt-get install -y google-cloud-cli google-cloud-cli-gke-gcloud-auth-plugin
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config
          kubectl apply -f argocd/argocd-app.yaml -n argocd
        shell: bash
